[build]
  publish = "dist"
  command = "gridsome build"
  
[template.environment]
  GRIDSOME_SHOPIFY_STOREFRONT = "MELVINHGF.NET™ Solutions Store"
  GRIDSOME_SHOPIFY_STOREFRONT_TOKEN = "Your Shopify Storefront Token"
